# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Custom Format
# format = '''
# [â”Œ](bold green) $path$all$character'''
# format = '''
# # ğŸ§¬â•­â•¼â”â”â”â”â”â”â”\[ ğŸŒ ğ™·ğšˆğ™¿ğ™´ğšğ™¿ğšğ™¾ğ™¼ğ™¿ğšƒ | ğŸ§¿ SYS: ALPHA-9 | âš LINK: STABLE \]â”â”â”â”â”â”â”â”â•¾â•®
# # âš™ï¸ â”‚ $username$directory$git_branch
# # âš—ï¸ â”‚ $package$rust$golang$nodejs$python
# # ğŸš€â•°â•¼â‰» 
# # '''
# format = """\
# ğŸŒ¸[â•­â”€â”€â”€â‰½ã€](#FF69B4) âœ¨ [ğ•„ğ”¸ğ”¾ğ•€â„‚ğ”¸ğ•ƒ ğ”¾ğ•€â„ğ•ƒ ğ•‹ğ”¼â„ğ•„ğ•€â„•ğ”¸ğ•ƒ](#FF69B4) âœ¨ [| ğŸŒˆ LINK: STABLE |](#B19CD9) ğŸ§ [SYSTEM: KAWAII-9 ã€‘â‰¼â”€â”€â”€â•®](#FF69B4)
# ğŸ¦Š[â”‚](#FF69B4) ğŸ’– USER: $username   ğŸ“ Fowder: $directory   ğŸŒ± Bwanchie: $git_branch
# ğŸ°[â”‚](#B19CD9) ğŸ“¦ Pwoject: $package   ó°Š¢ Gowang: $golang   îœ˜ Nodey: $nodejs   ğŸ Pywython: $python
# ğŸ’«[â•°â”€â”€â‰»](#B19CD9) 
# """

# Inserts a blank line between shell prompts
add_newline = true

# Directory name
[directory]
# style = "bold green"
# format = "ï„•  [$path]($style) "
format = "[$path]($style) "

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[â¯](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# language settings
[golang]
# symbol = "î˜§"
# symbol = "ğŸ‘ğŸ’¨"
# format = 'via [$symbol $version](bold cyan) '
format = '[$symbol $version](bold cyan) '
